# Generated by Django 4.1 on 2022-08-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "accepted"), (2, "pending"), (3, "rejected")], default=2
            ),
        ),
    ]
