# Generated by Django 4.1 on 2022-08-14 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_bankaccounttype_userbankaccount_useraddress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="loanType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField()),
                (
                    "need_collateral",
                    models.BooleanField(
                        help_text="does this type of Loan need Coollateral"
                    ),
                ),
                (
                    "need_guarantor",
                    models.BooleanField(
                        help_text="does this type of loan need a gurantor"
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        help_text="these include the category of people who will be interested in this particular product",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "min_amount_allowed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_amount_allowed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "interest_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "flate_rate"), (2, "reduncing_balance")]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "accepted"), (2, "pending"), (3, "rejected")]
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=10)),
                ("preferred_payment_date", models.DateField()),
                (
                    "payment_method",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "cash"), (2, "bank")]
                    ),
                ),
                ("tenure", models.IntegerField(null=True)),
                ("tenure_qualifier", models.CharField(max_length=50)),
                ("issue_date", models.DateField(null=True)),
                (
                    "payment_frequency",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "daily"),
                            (2, "monthly"),
                            (3, "quarterly"),
                            (4, "bi-annual"),
                            (5, "yearly"),
                        ]
                    ),
                ),
                ("fee", models.IntegerField(blank=True, null=True)),
                (
                    "fee_charge_method",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Deduct from principal balance"),
                            (2, "Add the fee on top of the loan"),
                        ],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_payment_account",
                        to="users.userbankaccount",
                    ),
                ),
                (
                    "loan_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loans.loantype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
