# Generated by Django 4.1 on 2022-08-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_alter_loan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="payment_frequency",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "daily"),
                    (2, "monthly"),
                    (3, "quarterly"),
                    (4, "bi-annual"),
                    (5, "yearly"),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="payment_method",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "cash"), (2, "bank")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="preferred_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="tenure_qualifier",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
